### ISSUE TITLE
UNet in Experiments

### ISSUE THREAD

**Issue by huynguyenbao** [TaoHuang2018/Neighbor2Neighbor#1]
Hi there, is the architecture of UNet you reported in your paper similar to blind spot UNet in High-Quality Self-Supervised Deep Image Denoising paper or just a simple UNet in medical image segmentation?

**Comment by TaoHuang2018** [comment]
Yes, the U-Net we used is similar to https://github.com/NVlabs/selfsupervised-denoising *without blind-spot design*.

**Comment by huynguyenbao** [comment]
The rotation method has been also in your implement yet?

**Comment by TaoHuang2018** [comment]
My implementation is without rotation which is used in blind-spot design.
